version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/laravel-demo
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 60
