version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/laravel-demo

hooks:
  AfterInstall:
    - location: aws/codedeploy/scripts/generate-env.sh
      timeout: 300
      runas: root
    - location: aws/codedeploy/scripts/set-permissions.sh
      timeout: 300
      runas: root
    - location: aws/codedeploy/scripts/setup-app.sh
      timeout: 300
      runas: root
