version: 0.2

env:
  variables:
    COMPOSER_CACHE_DIR: .cache/composer

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18.x
    commands:
      - apt update -y
      - echo Installing Composer...
      - curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - mkdir -p .cache/composer

  build:
    commands:
      - echo Installing PHP dependencies...
      - php /usr/local/bin/composer install --optimize-autoloader --no-dev
      - echo Clearing and caching Laravel...
      - php artisan optimize:clear
      - echo Installing NPM packages...
      - npm install
      - echo Building frontend assets...
      - npm run build

artifacts:
  files:
    - app/**/*
    - bootstrap/**/*
    - config/**/*
    - database/**/*
    - public/**/*
    - resources/**/*
    - routes/**/*
    - storage/**/*
    - vendor/**/*
    - composer.json
    - artisan
    - appspec.yml
    - aws/codedeploy/**/*

cache:
  paths:
    - .cache/composer/**/* 
    - node_modules/**/*
